servers:
  - hostname: clnode178.clemson.cloudlab.us
  - hostname: clnode134.clemson.cloudlab.us
  - hostname: clnode174.clemson.cloudlab.us
  - hostname: clnode173.clemson.cloudlab.us
  - hostname: clnode160.clemson.cloudlab.us
  - hostname: clnode162.clemson.cloudlab.us
  - hostname: clnode140.clemson.cloudlab.us
  - hostname: clnode167.clemson.cloudlab.us
  - hostname: clnode146.clemson.cloudlab.us
  - hostname: clnode136.clemson.cloudlab.us
  - hostname: clnode164.clemson.cloudlab.us
  - hostname: clnode151.clemson.cloudlab.us
  - hostname: clnode153.clemson.cloudlab.us
  - hostname: clnode157.clemson.cloudlab.us
